### ISSUE TITLE
Timezone issues

### ISSUE THREAD

**Issue by krmaxwell** [certsocietegenerale/FIR#13]
When I create a new incident, it appears to get stored in the DB with the wrong TZ (UTC+1?). This throws off my dashboard and incident views by 6 hours (which will of course vary for anyone not in UTC+1).

Below are screenshots of incidents I just created in a test instance at about 1320 local time, not 1920 as the DB seems to have.

---

![fir-dashboard](https://cloud.githubusercontent.com/assets/1624387/6854003/793c5b78-d3bc-11e4-9988-39f45074a8f9.png)

---

![fir-incident](https://cloud.githubusercontent.com/assets/1624387/6854004/793ce0fc-d3bc-11e4-9d26-e8b109ab5c87.png)

**Comment by krmaxwell** [comment]
I think the issue may be around https://github.com/certsocietegenerale/FIR/blob/7f1d550ab4de46ed1ed8d003730a0316ce71a61b/fir/config/base.py#L31 or so.

**Comment by krmaxwell** [comment]
Yup, this appears to be a configuration issue. The installation docs should probably make note of the parameters  `TIME_ZONE` and `USE_TZ` in `fir/config/base.py`.

**Comment by tomchop** [comment]
Pending making FIR timezone-aware, I've updated the documentation ([dev](https://github.com/certsocietegenerale/FIR/wiki/Setting-up-a-development-environment) and [prod](https://github.com/certsocietegenerale/FIR/wiki/Installation-on-a-production-environment)). I'll leave the issue open so that we remember fo fix this.

**Comment by krmaxweII** [comment]
Can you close my issue please.

**Comment by krmaxweII** [comment]
??
