### ISSUE TITLE
Failed to start uwsgi

### ISSUE THREAD

**Issue by seifreed** [certsocietegenerale/FIR#132]
Hi,

I'm trying to setup a FIR instance in production and I'm reciving this:

![image](https://cloud.githubusercontent.com/assets/1843119/18897678/9c0f28c4-852c-11e6-9801-468b7a8815aa.png)

**Comment by tomchop** [comment]
That's not something I've seen before. Can you please paste your uwsgi config file or the command-line you're using to launch it?

**Comment by seifreed** [comment]
Sure,

This is my config file:

![image](https://cloud.githubusercontent.com/assets/1843119/19042803/cced2d96-898d-11e6-901e-756ef38ee89a.png)

**Comment by tomchop** [comment]
Does the `/run` directory in `/home/f***/tools/FIR/` exist? And is it writeable by `www-data`?

**Comment by seifreed** [comment]
Yeah,

Seems all is correct!

![image](https://cloud.githubusercontent.com/assets/1843119/19045500/66d32cb6-8999-11e6-935b-90bc99315c43.png)

**Comment by tomchop** [comment]
According to [this](http://stackoverflow.com/questions/33246836/running-flask-app-with-uwsgi-and-nginx), the socket permissions need to be 666. Can you try using an actual TCP port instead of a socket?

**Comment by espressobeanie** [comment]
Tomchop, how do you do that?
FYI, good resource http://uwsgi-docs.readthedocs.io/en/latest/tutorials/Django_and_nginx.html

**Comment by gaelmuller** [comment]
Closing this for lack of response. Do not hesitate to reopen if needed.

**Comment by ryourff** [comment]
infosec@fir:~$ sudo service fir_uwsgi status
● fir_uwsgi.service - uWSGI instance for FIR
   Loaded: loaded (/etc/systemd/system/fir_uwsgi.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2020-07-28 09:23:25 UTC; 5s ago
  Process: 18383 ExecStart=/usr/bin/uwsgi --socket /home/infosec/FIR/run/fir.sock --chdir /home/infosec/FIR/ --plugins python --module fir.wsgi (code=exited, status=216/GROUP)
 Main PID: 18383 (code=exited, status=216/GROUP)

Jul 28 09:23:25 fir systemd[1]: fir_uwsgi.service: Service hold-off time over, scheduling restart.
Jul 28 09:23:25 fir systemd[1]: fir_uwsgi.service: Scheduled restart job, restart counter is at 5.
Jul 28 09:23:25 fir systemd[1]: Stopped uWSGI instance for FIR.
Jul 28 09:23:25 fir systemd[1]: fir_uwsgi.service: Start request repeated too quickly.
Jul 28 09:23:25 fir systemd[1]: fir_uwsgi.service: Failed with result 'exit-code'.
Jul 28 09:23:25 fir systemd[1]: Failed to start uWSGI instance for FIR.
infosec@fir:~$



kindly i need your help

**Comment by ryourff** [comment]
@tomchop kindly could you help me on this
