### ISSUE TITLE
FIR in french

### ISSUE THREAD

**Issue by ghost** [certsocietegenerale/FIR#160]
Hi !

Which files to modify to use Fir in french ?

Thanks

**Comment by lelardou** [comment]
Anybody ?

**Comment by y9mo** [comment]
i believe you have to change to following line in _fir/config/base.py_
from  
```LANGUAGE_CODE='en-us'```
to
```LANGUAGE_CODE='fr-FR'```

**Comment by CodyBr** [comment]
Already done but not yet in french

**Comment by gaelmuller** [comment]
I18N is managed by Django. You could look at the documentation in order to understand how that works:

https://docs.djangoproject.com/en/1.10/topics/i18n/translation/#how-django-discovers-language-preference

By default, FIR uses the LocaleMiddleware. This means that the language to use will be set by the client (the browser in the Accept-Language header), and not the server. If you want to enforce French for all users, you have to disable the LocaleMiddleware and set LANGUAGE_CODE to French.

**Comment by gcrahay** [comment]
Compiled translation messages are not committed (see [`.gitignore`](https://github.com/certsocietegenerale/FIR/blob/1fbb7e0bdf694f36de2a5389c8190875af18a461/.gitignore#L53)). So you need to compile them after installation for each `fir_*` app and `incidents`:

```bash
(fir-env) FIR $ cd incidents
(fir-env) incidents $ python ../manage.py compilemessages --settings=fir.config.production -l fr
(fir-env) incidents $ cd ../fir_whatever
(fir-env) fir_whatever $ python ../manage.py compilemessages --settings=fir.config.production -l fr
. . .
```
