### ISSUE TITLE
Fir_Celery

### ISSUE THREAD

**Issue by bjuditt** [certsocietegenerale/FIR#172]
Hi,

I do not understand how to use fir_celery

Thanks

**Comment by y9mo** [comment]
I added the `fir_celery` plugin to `fir` i might be able to help
can you be more specific

i added this `README` into a PR [#167](https://github.com/certsocietegenerale/FIR/pull/167) not accepted as of now, maybe this can help

## Install
Follow the generic plugin installation instructions in [the FIR wiki](https://github.com/certsocietegenerale/FIR/wiki/Plugins).

__Python Package Index (PyPI) requirements__
* celery
* redis

__Database requirement__
* Redis

The `fir_celery` plugin uses __redis__ as a broker and result backend. As a consequence, you should make sure to provide your FIR instance with the following ( `REDIS_HOST`, `REDIS_PORT` and `REDIS_DB` in the configuration file).


## Usage
Start a worker instance by using the __celery__ program. This is enough for testing/dev purpose but in production you will want to run your worker as a [daemon](http://docs.celeryproject.org/en/latest/userguide/daemonizing.html#daemonizing)
```bash
$ celery -A fir_celery.celeryconf worker -l info
```

### TODO
Improve this integration of celery as we add more tasks

**Comment by bjuditt** [comment]
Thanks for your help, I use FIR in a development environment and I do not see (even with your README) what it brings to FIR

**Comment by y9mo** [comment]
Celery integration into `fir` is to be used with `fir_artifacts_enrichment` plugin or any other plugin in need of asynchronous one shot or repeated task performed in the background

**Comment by bjuditt** [comment]
Do you have an example task

**Comment by y9mo** [comment]
you can look into `fir_artifacts_enrichment` the `tasks.py` file

**Comment by y9mo** [comment]
this module define a task called into the `fir_abuse` plugin performed upon each `Artifact` creation

**Comment by bjuditt** [comment]
And what does FIR_abuse do ?
I'm totaly lost

**Comment by y9mo** [comment]
# FIR ABUSE PLUGIN README

## Install
Follow the generic plugin installation instructions in [the FIR wiki](https://github.com/certsocietegenerale/FIR/wiki/Plugins).

| FIR plugin requirements   |                                                                                           |
| ------------------------- | ----------------------------------------------------------------------------------------- |
| fir_celery                | [[link]](https://github.com/certsocietegenerale/FIR/tree/master/fir_celery)               |
| fir_artifacts_enrichement | [[link]](https://github.com/certsocietegenerale/FIR/tree/master/fir_artifacts_enrichment) |

You should also make sure to configure your FIR instance so that it is able to send emails (see `EMAIL_HOST`, `EMAIL_PORT` and `REPLY_TO` in the configuration file).


## Usage

The `fir_abuse` plugin adds a **context menu** to be displayed when you right click on an artifact link on the incident details page.

Thanks to a **visual indicator** this context menu offers a feedback on the **enrichement task** fired in the background upon **each artifact creation** (provided by the two required plugins).

The enrichement task consists mainly in a **search** for an **abuse contact**. [[more info]](https://github.com/certsocietegenerale/FIR/tree/master/fir_artifacts_enrichment)

Clicking on **Send Abuse** in the context menu, opens a _Send Email Abuse_ modal form.

The form comes pre-filled with data from templates and contact info, which you can define from the FIR admin panel:

* __Abuse Templates__: `name`, `type`, `body`, `subject` and `incident_category` are the five attributes that define an abuse template. The abuse email's _subject_ and _body_ for a specific incident category are filled thanks to these templates. When trying to find a template, FIR will look for the most specific one.
* __Abuse Contact__: is a **_qualified contact information_** that helps define the upper part of the email form: `to`, `cc` and `bcc`. Each contact is specific to an `incident_category` and a `type`. FIR choose the right one depending on thoses parameters. The following variables are available by default in the context:
  * subject: name of the incident
  * bls: name of concerned business line
  * artifacts: dictionary of artifacts
  * incident_id: incident id
  * incident_category: category's name
  * artifact: artifact value
  * enrichment: enrichment raw content

If an __Abuse Contact__ exists it's always used to fill the upper part of the form, otherwise it's the __Email__ found through the enrichment process.

> The form also contain an __Enrichment tab__ providing the `raw` result of the enrichment task.

You should define your __Abuse Templates__ and qualified __Abuse Contact__ by connecting to FIR admin and adding objects to the "Abuse templates" and "Abuse contact" tables.

### TODO
Add the possibility to save the abuse email found through the enrichment task to the Abuse contact base

**Comment by y9mo** [comment]
the previous `README` will hopefully be merged soon into master (no idea on the ETA)

**Comment by bjuditt** [comment]
Can you put a screenshot of what fir_celry brings to the application.
Thank you

**Comment by y9mo** [comment]
The following picture displays the __incident details page__
* `fir_abuse` brings the __context menu__ you can access when you right click on an artifact and the __email abuse form__ displayed when you click on "send abuse"
* `fir_artifacts_enrichment` and `fir_celery` provide what is called __enrichment__ (WHOIS, network WHOIS) performed on each artifact

The circled element is a feedback on the enrichment task carried in the background.

![fir_abuse](https://cloud.githubusercontent.com/assets/5422376/22469314/dcc6d34c-e7cb-11e6-96f9-35ff6560d1f0.png)

This other picture show the __email abuse form__
* __pre-filled email recipient__ (`to`)
* the __enrichment tab__ in the modal
* the __email's body is supposed to be filled__ thanks to template you created

![fir_abuse_email](https://cloud.githubusercontent.com/assets/5422376/22469910/d38e2fd0-e7cd-11e6-92d7-e93c591b80aa.png)

**Comment by bjuditt** [comment]
Okay, I'm beginning to understand a little better. But is fir_celery in the django administration?

**Comment by y9mo** [comment]
Do you mean like being able to define new task? Not intended in that way for now.
Celery's integration will most likely evolve.
If you have any specific use case do not hesitate to submit a PR.

**Comment by bjuditt** [comment]
And enrichmeny, it sets itself automatically ? No template or other ?
Because it does not work, it does not put me the information of the centralops

**Comment by y9mo** [comment]
If you installed the plugin correctly `fir_enrichment` work out of the box.
The enrichment part is just to perform what's done otherwise through centralops

Templates are needed only by `fir_abuse` which uses them for some part of the email (allowing to to focus on review/edit and then send the email)

**Comment by bjuditt** [comment]
Hello, here is the result of the command `$ celery -A fir_celery.celeryconf worker -l info` : 

```
celery -A fir_celery.celeryconf worker -l info
Traceback (most recent call last):
  File "/usr/local/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/celery/__main__.py", line 14, in main
    _main()
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 326, in main
    cmd.execute_from_commandline(argv)
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 488, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 279, in execute_from_commandline
    argv = self.setup_app_from_commandline(argv)
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 489, in setup_app_from_commandline
    self._handle_user_preload_options(argv)
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 494, in _handle_user_preload_options
    user_preload = tuple(self.app.user_options['preload'] or ())
AttributeError: 'str' object has no attribute 'user_options'
```
PS : I do not know if I told you but I use the development version

**Comment by bjuditt** [comment]
UP

**Comment by gaelmuller** [comment]
The documentation is now available at https://github.com/certsocietegenerale/FIR/blob/master/fir_celery/README.md

Do not hesitate to reopen if needed.
