### ISSUE TITLE
Localization: Missing English Translations for the "Bale Categories"

### ISSUE THREAD

**Issue by chleggett** [certsocietegenerale/FIR#19]
There are no English translations for the Bale Categories.

**Comment by tomchop** [comment]
If you're talking about the admin section, we left it like this for now since changing the name would change the name of the tables. It will be fixed soon.

**Comment by DigiAngel** [comment]
Google translated:
(5> 33) computer hacking and other malicious attacks on computer systems of the bank by third parties
(5> 34) Other forms of crime against the bank's assets
(5> 35) Flights / scam / fraud committed by third parties (without complicity)
(5> 36) Flights by staff including service providers and trainees
(5> 37) Fraud on transactions by staff or with its complicity (employee bound by a contract of employment or subcontractor under a service contract)
(5> 38) Unauthorized use / misuse of privileged and confidential information by staff (as above)
(8> 44) failure of equipment
(8> 48) Weak logical security
(5) Fraud and other criminal activities
(7) Loss of operating means
(0) Other
(44) failure of information systems
(8) failure of information systems

**Comment by johnfellers** [comment]
last response on this was April 1 2015 stating it will be fixed soon. Will this be fixed?

**Comment by tomchop** [comment]
After messing around with i18n a little, we won't be fixing this. 

1. This does not deserve a .po translation file since the content is not being taken from templates but from the database itself and
2. it is therefore editable by anyone willing to translate the Basil categories into their own language
3. Furthermore, the list we include in the default fixture is not exhaustive

We can always change the "Bale category" name table its real English name ("Basel" category), but it seems non-critical as most people won't mess around with this.
The other solution to "internationalise" things a bit more (and decrease confusion) would be to remove the Basil categories from the template altogether.

Opinions?

**Comment by cameldelamotto** [comment]
What are bale categories used for exactly?

**Comment by gaelmuller** [comment]
They are only used in the "Stats > Major Incidents" webpage to do some reporting.

**Comment by cameldelamotto** [comment]
And where can we find bale categories and their associated number?

**Comment by tomchop** [comment]
It's really proper to the banking world. You can find more information on the [Basel II](https://en.wikipedia.org/wiki/Basel_II) and [Basel III](https://en.wikipedia.org/wiki/Basel_III) online.

**Comment by salian** [comment]
Why is this called Bale categories, the name seems to causes a bit of confusion. Could be called "Basel Risk Categories" to make it self-explanatory.

Google search for "Basel Risk Category" makes it obvious, whereas searching for "Bale Category" just brings up this page.

**Comment by chIeggett** [comment]
It may be time to close this issue ...
