### ISSUE TITLE
Notifications emails

### ISSUE THREAD

**Issue by Bahia18** [certsocietegenerale/FIR#254]
Hello,

I have installed everything necessary to receive notifications by email but it does not work and I have not any errors in the logs.

**Comment by udgover** [comment]
Can you give more details about how you set up email notifiers in django config? Were you able to send email via other means (such as python smtplib module)?

**Comment by Augustin-FL** [comment]
Hi,

In order to send emails, you need to set the following variables in your django configuration
```
EMAIL_HOST = 'smtp.myhost.com'
EMAIL_PORT = 25
EMAIL_HOST_USER = 'myUsername'
EMAIL_HOST_PASSWORD = 'myPassword'
EMAIL_FROM = 'fir@example.com'
REPLY_TO = None
EMAIL_CC = ['cc@example.com',]
EMAIL_BCC = ['bcc@example.com']
```
You should verify (using tools like `telnet` or `nc`) if your SMTP server is reachable and if you can login to it.

FIR uses Django's native libraries to manage SMTP connections. If you want to debug why you can't send mail, you may want to set up a django shell  and try to send a mail manually. The code handling emails can be found [here ](https://github.com/certsocietegenerale/FIR/blob/master/fir_email/helpers.py#L53-L54)and the django documentation is available [here](https://docs.djangoproject.com/en/4.2/topics/email/)

I will close this issue. Feel free to re-open it if you need more help !
