### ISSUE TITLE
Bad Gateway / Connection refused

### ISSUE THREAD

**Issue by shulsmann** [certsocietegenerale/FIR#260]
I've managed to install FIR, however i keep getting a '502 bad gateway' error.

The nginx error logs show the following error:

(111: Connection refused) while connecting to upstream, client: 10.127.255.66)

After hours of attempting to fix this myself I'm at a loss, can anyone help me fix this?

**Comment by udgover** [comment]
Can you please share your nginx configuration and how you installed and launched fir (uwsgi, unicorn, ...) ?

**Comment by renatoSeven** [comment]
have the same result when deploying via docker compose, with the help of portainer I was abble to see that the fir_web, fir_worker are down and only the proxy and DB are up, obviosly the 5XX error is the result because of this. after checking the logs on the web server I discovered that the django version is no longer compatible which results in tracebacks and the container goes down. is it possible to ajust code for new versions of python and OS(maybe minimum ubuntu server 18.04)?

**Comment by certsocietegenerale** [comment]
Closing as suggested in https://github.com/certsocietegenerale/FIR/issues/268#issuecomment-1043402652
