### ISSUE TITLE
Feature Request: External Authentication

### ISSUE THREAD

**Issue by chleggett** [certsocietegenerale/FIR#27]
Please consider adding External Authentication (LDAP, AD, Kerberos, etc.) to your roadmap.

**Comment by gcrahay** [comment]
FIR uses the default authentication system of Django, so you don't need to write code in order to use an external authentication system.

You can install a Django app like django-auth-ldap [1] in your virtualenv, add it to your AUTHENTICATION_BACKENDS tuple and configure it [2] to use a LDAP directory.

I successfully run a test instance where users are authenticated by RADIUS with a Freeradius backend and LDAP with an Active Directory backend.

I've never configured a Kerberos backend but there's an old (Django 1.6) app [3].

[1] https://pypi.python.org/pypi/django-auth-ldap/1.2.6
[2] http://pythonhosted.org/django-auth-ldap/ 
[3] https://github.com/02strich/django-auth-kerberos

**Comment by chleggett** [comment]
Thanks! I am new to Django and wasn't familiar with those options.

**Comment by Zenithar** [comment]
OpenID Connect ?

**Comment by tomchop** [comment]
We haven't worked on it for now but this might be of interest to you: https://launchpad.net/django-openid-auth

**Comment by mthIvt** [comment]
It may be time to close this issue ...

**Comment by chIeggett** [comment]
It may be time to close this incident ...
