### ISSUE TITLE
Artifacts are not loading Automatically.

### ISSUE THREAD

**Issue by Obad94** [certsocietegenerale/FIR#283]
I have been working with artifacts, earlier it was running perfectly and all the artifacts were loading automatically from the related files. but now after a few weeks, it's not loading automatically. I can only see the hashes of the uploaded files but no contents such as IP, URL, or email addresses are shown. 
I have tried pdf, HTML, CSV, txt, and xlsx but nothing works.

**Comment by Augustin-FL** [comment]
Hi,

I may be wrong, but from my understanding uploaded files are not (and have never been) scanned for artifacts in them. Their hashes [are calculated and added as artifact](https://github.com/certsocietegenerale/FIR/blob/master/fir_artifacts/files.py#L33-L56), but their content is not analyzed.

IP/URL/emails artifacts are calculated from the ticket description, comments or nuggets only.

Could you please check on the "earlier" tickets if the artifacts have been loaded because of some comment on the ticket ?

**Comment by Obad94** [comment]
Ohh Yeah, Sorry for the inconvenience. I totally forgot the process flow. well, by the way, is there any possibility to add a new feature to analyze files that can help to extract information (IP, hashes, Emails, URLs) from the uploaded files?

Thank you for the quick response you are a savior.

**Comment by Augustin-FL** [comment]
Hummm ...to be honnest I am not sure this feature would be desirable : attached files are not supposed to contain evidence (Evidence should be added as comment or nugget instead). There is a risk of adding misleading/wrong artifacts.

Also, this feature would be very complex to implement, given the high number of files to support (from .msg/.eml to office & HTML documents...)

**Comment by Obad94** [comment]
Got your point.  Thank you for the information.
