### ISSUE TITLE
How to enable HTTPS

### ISSUE THREAD

**Issue by giglioroninomicon** [certsocietegenerale/FIR#325]
Hi there, I've installed FIR on Ubuntu 22.04 using the production instructions and detvan's follow up addendum. Everything appears to be working on http port 80. I would like to be able to use HTTPS and have any HTTP calls be redirected. Can you point me in the direction of the config files I need to update (uwsgi and/or nginx)? I have generated self signed certs and am tiptoeing my way along since I am outside of my wheelhouse but am learning loads. Also appreciate you allowing us to use this awesome tool. Thanks!

**Comment by Augustin-FL** [comment]
Hello,

In order to enable HTTPS on your website, you need to update the nginx config files. You can follow [this tutorial](https://www.digitalocean.com/community/tutorials/how-to-create-a-self-signed-ssl-certificate-for-nginx-in-ubuntu) if you want to use a self-signed certificate, or [this one](https://netshopisp.medium.com/how-to-install-certbot-on-debian-11-for-lets-encrypt-ssl-768562a8de0) if you want to use a valid, trusted certificate.

**Comment by Augustin-FL** [comment]
I'm closing this issue, feel free to re-open it if needed
