### ISSUE TITLE
Stored XSS in the comment field

### ISSUE THREAD

**Issue by aleksf** [certsocietegenerale/FIR#50]
Comment is vulnerable to XSS

PoC: submit following as POST request body:

csrfmiddlewaretoken=9zdYmbOteXVHKiJBezS05DT23diCYDwU&action=6&date=2015-12-18+13%3A41&comment=“><script>alert(1)</script>

Subsequent visit of the event will result in popup

**Comment by p-l-** [comment]
The comment does not show properly because the data of the POST request is not properly formatted. The data should read: 

    csrfmiddlewaretoken=9zdYmbOteXVHKiJBezS05DT23diCYDwU&action=6&date=2015-12-18+13%3A41&comment=“><script>alert(1)</script>

**Comment by aleksf** [comment]
Thanks @p-l- - github filter stripped it off

**Comment by tomchop** [comment]
Thanks for bringing this up. This issue comes from the fact that you can paste any HTML into the comment (and incident body) textareas. This had the nice side-effect of preserving the structure of most of the things you would paste from the web (tables, divs, etc.). The downside is XSS, which is of course a major issue.

These are the solutions we're considering:
* **Migrate from rich-text editing to markdown** - cleaner, homogeneous formatting, less security issues, but we won't be able to copypasta content from the web (this is probably the one we'll go for)
* **Remove scripting elements from user-input HTML** - a hard problem, we need to find a lib for this that we'll have to keep up-to-date

Any suggestions are more than welcome.

**Comment by p-l-** [comment]
As a FIR (enthusiast) user, I'd like to give my opinion on this one:
  - Protecting against XSS while allowing user-controlled HTML is hard. You know that if you've written or analysed a Webmail or a Forum application.
  - The current editor in FIR is its major defect IM (not so H) O: it's hard to get exactly what you want (maybe @carolineLe wants to add something here ;-) ).

Using markdown (or rst, for that matter) would be a great move, giving FIR a cool editor (ideally with Write & Preview tabs, a la Github) and closing the door to such XSS bugs.

**Comment by byt3smith** [comment]
I also support using Markdown instead of the current editor. I have tested a little bit using the Django-Markdown-Deux, which does the job, but would be nice to also have a built-in Markdown preview as part of the editor

**Comment by tomchop** [comment]
This is adressed in @gcrahay's PR. Thanks!
