### ISSUE TITLE
Don't find the default username and password

### ISSUE THREAD

**Issue by danje57** [certsocietegenerale/FIR#52]
Hello,

I've just installed FIR in development version.
However I can't find the default username/password to use, do you have it?

Regards

**Comment by gaelmuller** [comment]
Hello,

Did you follow the documentation (https://github.com/certsocietegenerale/FIR/wiki/Setting-up-a-development-environment) in order to install your development version ?

If you did, you should have imported initial data and test users (login: admin, password: admin / login: dev, password: dev).

**Comment by danje57** [comment]
Ohh yes thx, didn't see it! sorry
