### ISSUE TITLE
Issue running ./manage.py syncdb for Development Install

### ISSUE THREAD

**Issue by Catopuss** [certsocietegenerale/FIR#53]
Running into an issue when I get to the step of ./manage.py syncdb it would appear that syncdb is no longer an option based on what I'm seeing in the help. Also found an article in stack overflow stating that syncdb has gone away and to use migrate. 

When I run ./manage.py migrate instead I get an error of: 

File "./manage.py", line 8 in <module> 
     from django.core.management import execute_from_command_line
ImportError: no module named django.core.management

then dumps me back to my virtual environment.

**Comment by Erreinion** [comment]
When running the Dockerfile, I get the error: 

Unknown command: 'syncdb'
Type 'manage.py help' for usage.

I'm assuming this is the same issue.

**Comment by gaelmuller** [comment]
Sorry about that. It seems syndb was removed in Django 1.9 that we are now using (since yesterday).

I added the missing migrations and updated the documentation, so it should work fine now with only `./manage.py migrate` (the Dockerfile has also been updated).

@Catopuss, I could not reproduce your error when running `migrate`. This seems to indicate that Django is not properly installed. Please provide us with the output of `pip install -r requirements.txt` in your virtualenv if you are still having this error message.

**Comment by Catopuss** [comment]
I finally got it to work. You were probably right something must of got messed up during the Django install. I wiped it clean and started over and it worked now. Thanks.
