### ISSUE TITLE
Feature Request: Incident template todo's

### ISSUE THREAD

**Issue by reynas** [certsocietegenerale/FIR#98]
It could be interesting to add "todo's" to the incident templates, I didn't see a possibility to do this now;
What are your thoughts on this?

**Comment by gaelmuller** [comment]
This is not directly possible at the moment. You can however create todo templates that could answer your use case. Please have a look at `fir_todo`'s README (https://github.com/certsocietegenerale/FIR/tree/master/fir_todos).

Todo templates are for now more than enough for our own needs, which means we will probably not work on this feature request anytime soon. If anyone wants to work on this though, contributions are always welcome.

**Comment by erturpin** [comment]
Yeah I agree with @gaelmuller, we have templated todo lists now so adding to the incident template isn't as helpful. In our implementation I actually added the logic for enumerating todo templates to the API so that the todo lists can be templated out on incidents regardless of if they were created by a user directly or by an API call.

**Comment by tomchop** [comment]
`fir_todos` should take care of this. Closing.
